site_name: ç©ºç™½é˜´å½±çš„ç¬”è®°æœ¬
site_author: ç©ºç™½é˜´å½±
site_url: ''

repo_url: https://github.com/kbyy123/notebook.git
repo_name: kbyy123/notebook
use_directory_urls: false    # åŠ ä¸Šè¿™å¥åæ‰èƒ½æ˜¾ç¤ºç”¨ html img ç›¸å¯¹è·¯å¾„æ’å…¥çš„å›¾ç‰‡

theme:
  name: material
  language: zh  # è®¾ç½®ä¸ºä¸­æ–‡
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view      # åœ¨é¡µé¢å³ä¸Šè§’æ·»åŠ â€œç¼–è¾‘æ­¤é¡µâ€æˆ–â€œæŸ¥çœ‹æºç â€çš„æŒ‰é’®
    - content.code.copy        # ä»£ç å—ä¸€é”®å¤åˆ¶
    - content.code.annotate    # æ³¨é‡Šæ°”æ³¡ 
    - content.footnote.tooltips
    - navigation.footer        # åœ¨é¡µé¢åº•éƒ¨æ˜¾ç¤ºâ€œä¸Šä¸€ç¯‡/ä¸‹ä¸€ç¯‡â€å¯¼èˆª
    - navigation.indexes       # å…è®¸ç‚¹å‡»åˆ†ç±»å¤§ç±»åç›´æ¥è¿›å…¥è¯¥ç›®å½•çš„ index.md
    - navigation.path          # åœ¨é¡µé¢é¡¶éƒ¨æ˜¾ç¤ºå½“å‰é¡µé¢çš„è·¯å¾„
    - navigation.prune         # æ€§èƒ½ä¼˜åŒ–
    - navigation.tabs           
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow               # å³ä¾§ç›®å½•éšæ»šåŠ¨é«˜äº®
    - content.code.copy        # ä»£ç å—ä¸€é”®å¤åˆ¶
  font:
    text: false
    code: JetBrains Mono

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:       # LaTeX æ•°å­¦å…¬å¼æ”¯æŒ
      generic: true
      smart_dollar: true  # å…³é”®ï¼šé˜²æ­¢ Markdown å¼•æ“å¹²æ‰°ç¾å…ƒç¬¦å·å†…çš„å†…å®¹
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html  # æ ¸å¿ƒï¼šå…è®¸åœ¨ <div> æ ‡ç­¾å†…è§£æ Markdown    
  - pymdownx.superfences       # æ”¯æŒæ›´å¤æ‚çš„ä»£ç å—åµŒå¥—
  - pymdownx.details           # æ”¯æŒæŠ˜å å— (Admonitions)

extra_css:
  - css/custom.css
  - css/timestamp.css
  - css/home.css
  - css/font.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/typed.js

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true  # å¼€å¯åˆ›å»ºæ—¶é—´
      type: datetime              # æ˜¾ç¤ºå®Œæ•´æ—¥æœŸæ—¶é—´
      locale: zh                  # ä½¿ç”¨ä¸­æ–‡ç•Œé¢
      timezone: Asia/Shanghai     # è®¾ç½®æ—¶åŒº
  - changelog

nav:
  - ğŸ«ä¸»é¡µ: index.md
  - ğŸ“Šæ•°å­¦: 
    - math/index.md
    - å¤šå˜é‡å¾®ç§¯åˆ†:
      - math/multivariable-calculus/index.md
      - math/multivariable-calculus/1.md
      - math/multivariable-calculus/2.md
      - math/multivariable-calculus/3.md
